<a href="https://colab.research.google.com/github/MuhammadNihalImran/ML_Lab_Tasks/blob/main/ML_LAB_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset("titanic")

In [3]:
df.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [4]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [5]:
df.fillna({'age':df['age'].mean()},inplace=True)

In [6]:
df.dropna(subset=['embarked'],inplace=True)

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])
df['sex']

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: sex, Length: 889, dtype: int64

In [8]:
df = pd.get_dummies(df,columns=['embarked'],drop_first=True)

In [9]:
df

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone,embarked_Q,embarked_S
0,0,3,1,22.000000,1,0,7.2500,Third,man,True,NaN,Southampton,no,False,False,True
1,1,1,0,38.000000,1,0,71.2833,First,woman,False,C,Cherbourg,yes,False,False,False
2,1,3,0,26.000000,0,0,7.9250,Third,woman,False,NaN,Southampton,yes,True,False,True
3,1,1,0,35.000000,1,0,53.1000,First,woman,False,C,Southampton,yes,False,False,True
4,0,3,1,35.000000,0,0,8.0500,Third,man,True,NaN,Southampton,no,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,13.0000,Second,man,True,NaN,Southampton,no,True,False,True
887,1,1,0,19.000000,0,0,30.0000,First,woman,False,B,Southampton,yes,True,False,True
888,0,3,0,29.699118,1,2,23.4500,Third,woman,False,NaN,Southampton,no,False,False,True
889,1,1,1,26.000000,0,0,30.0000,First,man,True,C,Cherbourg,yes,True,False,False
890,0,3,1,32.000000,0,0,7.7500,Third,man,True,NaN,Queenstown,no,True,True,False

In [13]:
new_df = df[['age','fare','sex','pclass']]
new_df.sample(5)

           age     fare  sex  pclass
295  29.699118  27.7208    1       1
826  29.699118  56.4958    1       3
441  20.000000   9.5000    1       3
93   26.000000  20.5750    1       3
335  29.699118   7.8958    1       3

In [15]:
from sklearn.preprocessing import StandardScaler

In [18]:
ss = StandardScaler()
df[new_df.columns]  = ss.fit_transform(new_df)

In [19]:
df.sample(5)

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone,embarked_Q,embarked_S
677,1,0.825209,-1.359911,-0.899111,0,0,-0.448061,Third,woman,False,NaN,Southampton,yes,True,False,True
16,0,0.825209,0.735342,-2.133577,4,1,-0.059829,Third,child,False,NaN,Queenstown,no,False,True,False
418,0,-0.373501,0.735342,0.026738,0,0,-0.384475,Second,man,True,NaN,Southampton,no,True,False,True
57,0,0.825209,0.735342,-0.088993,0,0,-0.500659,Third,man,True,NaN,Cherbourg,no,True,False,False
69,0,0.825209,0.735342,-0.281878,2,0,-0.471802,Third,man,True,NaN,Southampton,no,False,False,True

In [20]:
x = df.drop(columns=['survived'])
y = df['survived']

In [21]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [22]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((711, 15), (178, 15), (711,), (178,))